version: '3'

services:
  nexus:
    image: sonatype/nexus3:3.9.0
    ports:
     - "8081:8081"

  iqserver:
    image: sonatype/nexus-iq-server:1.45.0
    ports:
     - "8070:8070"
     - "8071:8071"
    volumes:
      - ./conf/iqserver.yml:/etc/nexus-iq-server/config.yml:ro
