[[constraint]]
  name = "github.com/cloudogu/go-cas"
  version = "2.2.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/vulcand/oxy"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"
